#CREAR 
    #CARPETA CLOUD
    #ARCHIVO CLOUD
#ELMINAR EN CLOUD
#COPIAR:
    #CLOUD->CLOUD
#MOVER(TRANSFERIR)
    #CLOUD->CLOUD
    #CLOUD->LOCAL
    #CLOUD->LOCAL
#RENOMBRAR
    #CARPETA CLOUD
    #ARCHIVO CLOUD
#SUSTITUIR
#AGREGARA CONTENIDO